# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2d4196327110f125c9e39458144b8ce236bc0e3e195131a38138c6af49c36befe720e98b6eb578a319ee3820861b9403c3de42c5338c7257a9d83369024c1a3

test:
  secret_key_base: f1c5c10cf02c44a877cc76d78524279f4f3a69269e5f70a7f4457125e5118894a9c11cb91c3fc0f9368d1cc7d5b7dbdaf827f9cad6b56a6513f89a430b51fd1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
